# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17guQAzblIIB4xs-bi_4ZuJe2rdwiB0P-

#Pandas
import pandas as pd
"""

import pandas as pd
ser=pd.Series([2,4,3,6,4,3])
ser

ser2=pd.Series(['orange','pinck','skyblue','yellow'])
ser2

ser3=pd.Series([1,'orange',[2,5]])
ser3

ser2[1:3]

ser[1:4]

ser[-3:-1]

ser4=pd.Series([2,7,3,2,3],index=['f1','f20','f3','f4','f5'])
ser4

ser4['f2':'f4']

ser4[-4:-1]

#Dataframe
df=pd.DataFrame([[2,4,5,4,6],[5,6,7,8,2],[3,5,4,2,2]])
df

df.columns=['c1','c2','c3','c4','c5']
df.index=['r1','r2','r3']

df

import numpy as np
exdf=pd.DataFrame(np.arange(5*10).reshape(10,5))
#exdf=pd.DataFrame([[2,3,4,2,3],np.array([1,2,3,4,5])*4])
exdf

d={'name':['lokesh','sowjanya','bhargav',],'age':[2,3,4],'gender':['m','f','b']}
d

pd.DataFrame(d)

/mtcars.csv

df=pd.read_csv("/mtcars.csv")
df

df.head()

df.tail()

df.head(15)

df.tail(20)

df.shape()

df.shape

df.info()

df.mpg

df.model

df.gear

df.cyl

df[0:8]

df['mode;':'vs']

df[::8]

df.iloc[:,;8]

df[:,:9]

df.iloc[:,:8]

df.loc[1:,:6]

df.loc[3:25,["model",'qsec']]

df.loc[1:25,'model':'qsec']

df.loc[1:21,['model']]

df.isnull().any()

df.isnull.sum()

df

df.iloc[4:,:9]

df.iloc[:4,:10]

df.iloc[2:18:,4:10]

df.iloc[:,4:10]

